apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mariadb-operator.fullname" . }}-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
      - persistentvolumeclaims
    verbs:
      - list
      - watch
      - create
      - patch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - list
      - watch
      - create
      - patch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - list
      - watch
      - create
      - patch
  - apiGroups:
      - database.mmontes.io
    resources:
      - backupmariadbs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - database.mmontes.io
    resources:
      - backupmariadbs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - database.mmontes.io
    resources:
      - databasemariadbs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - database.mmontes.io
    resources:
      - databasemariadbs/finalizers
    verbs:
      - update
  - apiGroups:
      - database.mmontes.io
    resources:
      - databasemariadbs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - database.mmontes.io
    resources:
      - grantmariadbs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - database.mmontes.io
    resources:
      - grantmariadbs/finalizers
    verbs:
      - update
  - apiGroups:
      - database.mmontes.io
    resources:
      - grantmariadbs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - database.mmontes.io
    resources:
      - mariadbs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - database.mmontes.io
    resources:
      - mariadbs/finalizers
    verbs:
      - update
  - apiGroups:
      - database.mmontes.io
    resources:
      - mariadbs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - database.mmontes.io
    resources:
      - restoremariadbs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - database.mmontes.io
    resources:
      - restoremariadbs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - database.mmontes.io
    resources:
      - usermariadbs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - database.mmontes.io
    resources:
      - usermariadbs/finalizers
    verbs:
      - update
  - apiGroups:
      - database.mmontes.io
    resources:
      - usermariadbs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - list
      - watch
      - create
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mariadb-operator.fullname" . }}-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mariadb-operator.fullname" . }}-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create