apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-from-backup-scheduled
spec:
  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Gi
    accessModes:
      - ReadWriteOnce

  bootstrapFrom:
    backupRef:
      name: backup-scheduled
    targetRecoveryTime: 2023-12-28T09:00:00Z
