apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mariadb-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mariadb-proxy-role
subjects:
  - kind: ServiceAccount
    name: mariadb-controller-manager
    namespace: mariadb-system
