# permissions for end users to edit backupmariadbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backupmariadb-editor-role
rules:
- apiGroups:
  - database.mmontes.io
  resources:
  - backupmariadbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.mmontes.io
  resources:
  - backupmariadbs/status
  verbs:
  - get
