# permissions for end users to edit databasemariadbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databasemariadb-editor-role
rules:
- apiGroups:
  - database.mmontes.io
  resources:
  - databasemariadbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.mmontes.io
  resources:
  - databasemariadbs/status
  verbs:
  - get
