# permissions for end users to view exportermariadbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exportermariadb-viewer-role
rules:
- apiGroups:
  - database.mmontes.io
  resources:
  - exportermariadbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.mmontes.io
  resources:
  - exportermariadbs/status
  verbs:
  - get
