# permissions for end users to edit exportermariadbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exportermariadb-editor-role
rules:
- apiGroups:
  - database.mmontes.io
  resources:
  - exportermariadbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.mmontes.io
  resources:
  - exportermariadbs/status
  verbs:
  - get
