# permissions for end users to edit grantmariadbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grantmariadb-editor-role
rules:
- apiGroups:
  - database.mmontes.io
  resources:
  - grantmariadbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.mmontes.io
  resources:
  - grantmariadbs/status
  verbs:
  - get
