# permissions for end users to view grantmariadbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grantmariadb-viewer-role
rules:
- apiGroups:
  - database.mmontes.io
  resources:
  - grantmariadbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.mmontes.io
  resources:
  - grantmariadbs/status
  verbs:
  - get
