apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mariadb-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mariadb-leader-election-role
subjects:
  - kind: ServiceAccount
    name: mariadb-controller-manager
    namespace: mariadb-system
