# permissions for end users to view monitormariadbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitormariadb-viewer-role
rules:
- apiGroups:
  - database.mmontes.io
  resources:
  - monitormariadbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.mmontes.io
  resources:
  - monitormariadbs/status
  verbs:
  - get
