# permissions for end users to edit monitormariadbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitormariadb-editor-role
rules:
- apiGroups:
  - database.mmontes.io
  resources:
  - monitormariadbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.mmontes.io
  resources:
  - monitormariadbs/status
  verbs:
  - get
