# permissions for end users to edit restoremariadbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restoremariadb-editor-role
rules:
- apiGroups:
  - database.mmontes.io
  resources:
  - restoremariadbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.mmontes.io
  resources:
  - restoremariadbs/status
  verbs:
  - get
