---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - database.mmontes.io
  resources:
  - backupmariadbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.mmontes.io
  resources:
  - backupmariadbs/finalizers
  verbs:
  - update
- apiGroups:
  - database.mmontes.io
  resources:
  - backupmariadbs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - database.mmontes.io
  resources:
  - mariadbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.mmontes.io
  resources:
  - mariadbs/finalizers
  verbs:
  - update
- apiGroups:
  - database.mmontes.io
  resources:
  - mariadbs/status
  verbs:
  - get
  - patch
  - update
