# permissions for end users to view usermariadbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: usermariadb-viewer-role
rules:
- apiGroups:
  - database.mmontes.io
  resources:
  - usermariadbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.mmontes.io
  resources:
  - usermariadbs/status
  verbs:
  - get
