# permissions for end users to edit usermariadbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: usermariadb-editor-role
rules:
- apiGroups:
  - database.mmontes.io
  resources:
  - usermariadbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.mmontes.io
  resources:
  - usermariadbs/status
  verbs:
  - get
