apiVersion: mariadb.mmontes.io/v1alpha1
kind: Backup
metadata:
  name: mariadb
spec:
  mariaDbRef:
    name: mariadb
  schedule:
    cron: "*/1 * * * *"
  maxRetention: 30d
  storage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 100Mi
      accessModes:
        - ReadWriteOnce