# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: usermariadbs.database.mmontes.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: mariadb-system
          name: webhook-service
          path: /convert
      conversionReviewVersions:
        - v1
