apiVersion: database.mmontes.io/v1alpha1
kind: BackupMariaDB
metadata:
  name: backup-scheduled
spec:
  mariaDbRef:
    name: mariadb
  waitForMariaDb: true
  schedule:
    cron: "*/1 * * * *"
    suspend: false
  storage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 100Mi
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
