apiVersion: database.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-min
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  image:
    repository: mariadb

  storage:
    className: standard
    size: 100Mi
