apiVersion: database.mmontes.io/v1alpha1
kind: ExporterMariaDB
metadata:
  name: mariadb-exporter
spec:
  mariaDbRef:
    name: mariadb
  image:
    repository: prom/mysqld-exporter
    tag: "v0.14.0"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 512Mi
