apiVersion: database.mmontes.io/v1alpha1
kind: UserMariaDB
metadata:
  name: user
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: user
    key: password
  maxUserConnections: 20
