apiVersion: database.mmontes.io/v1alpha1
kind: GrantMariaDB
metadata:
  name: user
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
  database: "*"
  table: "*"
  username: user
  grantOption: true
