apiVersion: database.mmontes.io/v1alpha1
kind: MonitorMariaDB
metadata:
  name: monitor
spec:
  mariaDbRef:
    name: mariadb
  exporter:
    image:
      repository: prom/mysqld-exporter
      tag: "v0.14.0"
      pullPolicy: IfNotPresent
  interval: 10s
  scrapeTimeout: 10s
